#ifndef PROTOCOL_H
#define PROTOCOL_H

// This file is to ensure that all parts of the network agree 
// on the same port numbers, command names, and error codes

// Network definitions
#define NM_PORT 8000
#define NM_IP "10.1.40.87"

// Buffer size
#define MAX_BUFFER 4096
#define MAX_FILE_BUFFER 2048

// Registration commands
#define CMD_REG_CLIENT "REG_CLIENT"
#define CMD_REG_SS "REG_SS"

// Universal error/ success codes
#define SUCCESS 200
#define ERROR_MALFORMED_REQUEST 400
#define ERROR_UNAUTHORISED 401
#define ERROR_FILE_NOT_FOUND 404
#define ERROR_UNKNOWN_COMMAND 405
#define ERROR_SERVER_ERROR 500 
#define ERROR_FILE_ALREADY_EXISTS 409
#define ERROR_NO_STORAGE_SERVERS 503
#define ERROR_CANNOT_CREATE_FILE 500
#define ERROR_CANNOT_DELETE_FILE 501
#define ERROR_USER_NOT_FOUND 440
#define ERROR_CANNOT_REMOVE_ACCESS_FROM_OWNER 441
#define ERROR_SENTENCE_LOCKED 423
#define ERROR_PREVIOUS_SENTENCE_INCOMPLETE 424 // Custom code for specific rule
#define ERROR_INVALID_INDEX 425
#define ERROR_NO_UNDO_RECORD 404

// Storage Server commands
#define CMD_SS_CREATE "SS_CREATE"
#define CMD_SS_DELETE "SS_DELETE"
#define CMD_SS_READ "SS_READ"
#define CMD_SS_STREAM "SS_STREAM"
#define CMD_WRITE "WRITE"
#define CMD_ETIRW "ETIRW"
#define CMD_UNDO "UNDO"
#define CMD_SS_UPDATE_META "SS_UPDATE_META"

// Server reply messages
#define MSG_SUCCESS "200 SUCCESS\n"
#define MSG_MALFORMED "400 ERROR_MALFORMED_REQUEST\n"
#define MSG_UNKNOWN "405 ERROR_UNKNOWN_COMMAND\n"
#define MSG_UNAUTHORIZED "401 ERROR_UNAUTHORIZED\n"
#define MSG_FILE_NOT_FOUND "404 ERROR_FILE_NOT_FOUND\n"
#define MSG_FILE_ALREADY_EXISTS "409 ERROR_FILE_ALREADY_EXISTS\n"
#define MSG_NO_STORAGE_SERVERS "503 ERROR_NO_STORAGE_SERVERS\n"
#define MSG_CANNOT_CREATE_FILE "500 ERROR_CANNOT_CREATE_FILE\n" 
#define MSG_CANNOT_DELETE_FILE "501 ERROR_CANNOT_DELETE_FILE\n"
#define MSG_USER_NOT_FOUND "440 ERROR_USER_NOT_FOUND\n"
#define MSG_CANNOT_REMOVE_ACCESS_FROM_OWNER "441 ERROR_CANNOT_REMOVE_ACCESS_FROM_OWNER\n"
#define MSG_SENTENCE_LOCKED "423 ERROR_SENTENCE_LOCKED\n"
#define MSG_PREVIOUS_SENTENCE_INCOMPLETE "424 ERROR_PREVIOUS_SENTENCE_INCOMPLETE\n"
#define MSG_INVALID_INDEX "425 ERROR_INVALID_INDEX\n"
#define MSG_NO_UNDO_RECORD "404 ERROR_NO_UNDO_RECORD\n"

#endif